# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ibi4KgpYb92drNaTknFolviJiNpU0eY

# Import
"""

!pip install pandas numpy matplotlib seaborn textblob nltk wordcloud

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from textblob import TextBlob
import nltk
from wordcloud import WordCloud
import re

nltk.download('punkt')

"""# Upload Data set"""

df = pd.read_csv('/content/chatgpt_reviews.csv')
display(df.head())

"""# Data checking and cleaning

"""

df.info()

df.describe()

df.isnull().sum()

df.dropna(subset=['Review'], inplace=True)

display(df.isnull().sum())

df = df.drop_duplicates(subset=['Review Id']).copy()

df['Review Date'] = pd.to_datetime(df['Review Date'], errors='coerce')

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

df['clean_review'] = df['Review'].apply(clean_text)

"""# SENTIMENT ANALYSIS AND DISTRIBUTION"""

def get_sentiment(text):
    score = TextBlob(text).sentiment.polarity

    if score > 0:
        return "Positive"
    elif score < 0:
        return "Negative"
    else:
        return "Neutral"

df['sentiment'] = df['clean_review'].apply(get_sentiment)

plt.figure(figsize=(6,4))
sns.countplot(x='sentiment', data=df)
plt.title("Sentiment Distribution")
plt.show()

"""# ISSUE IDENTIFICATION

"""

negative_reviews = df[df['sentiment'] == 'Negative']

text = " ".join(negative_reviews['clean_review'])

wordcloud = WordCloud(width=800, height=400).generate(text)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud)
plt.axis('off')
plt.title("Common Issues in Negative Reviews")
plt.show()

"""# TIME SERIES ANALYSIS"""

df['month'] = df['Review Date'].dt.to_period('M')

trend = df.groupby(['month', 'sentiment']).size().unstack().fillna(0)

trend

"""# SENTIMENT TREND GRAPH"""

trend.plot(figsize=(10,5))
plt.title("Sentiment Trend Over Time")
plt.xlabel("Month")
plt.ylabel("Number of Reviews")
plt.show()

"""#Sentiment Heatmap"""

plt.figure(figsize=(10,5))
sns.heatmap(trend.T, annot=True, fmt=".0f")
plt.title("Sentiment Heatmap")
plt.show()

"""# TOP ISSUE WORDS"""

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

# Add custom unwanted words (VERY IMPORTANT)
custom_words = {
    'wrong','cant','dont','doesnt','please','good','bad','worst',
    'time','answer','answers','chat','information','give',
    'work','working','sometimes','really','even','just'
}

stop_words = stop_words.union(custom_words)

def clean_text_advanced(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)

    words = text.split()

    # Remove stopwords and short words
    words = [word for word in words
             if word not in stop_words and len(word) > 3]

    return " ".join(words)

df['clean_review'] = df['Review'].apply(clean_text_advanced)

issue_keywords = [
    'error','issue','problem','fail','failed','crash','bug',
    'slow','lag','not working','doesnt work','unable',
    'login issue','network','connection','stuck','freeze',
    'wrong answer','incorrect','bad','worst','broken'
]

remove_words = [
    'good','great','helpful','amazing','best',
    'game changer','artificial intelligence',
    'extremely helpful','nice','love'
]

negative_reviews = df[df['sentiment'] == 'Negative']

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=2000,
    ngram_range=(2,3),
    stop_words='english'
)

X = vectorizer.fit_transform(negative_reviews['clean_review'])

feature_names = vectorizer.get_feature_names_out()
scores = X.sum(axis=0).A1

tfidf_df = pd.DataFrame({
    'Phrase': feature_names,
    'Score': scores
})

# Keep phrases that contain issue keywords
tfidf_df = tfidf_df[
    tfidf_df['Phrase'].str.contains('|'.join(issue_keywords))
]

tfidf_df = tfidf_df[
    ~tfidf_df['Phrase'].str.contains('|'.join(remove_words))
]

tfidf_df = tfidf_df[
    tfidf_df['Phrase'].str.contains(
        'error|fail|crash|issue|problem|slow|bug|unable|not working'
    )
]

"""# ISSUE WORDS VISUALIZATION

"""

top_phrases = tfidf_df.head(10)

plt.figure(figsize=(10,5))
sns.barplot(x='Score', y='Phrase', data=top_phrases)
plt.title("Top Meaningful Issues (TF-IDF Phrases)")
plt.show()

"""## **INSIGHTS FROM THE ANALYSIS**

### **1. Overall Sentiment Distribution**

From the "Sentiment Distribution" plot, we observe that the majority of reviews are **Positive**, followed by a substantial number of **Neutral** reviews, and a smaller but significant portion of **Negative** reviews. This indicates a generally favorable user perception, but also highlights areas where experiences are either not strongly positive or outright negative.

### **2. Sentiment Trend Over Time**

The "Sentiment Trend Over Time" graph  and the "Sentiment Heatmap" show the evolution of sentiment:

*   **Growth in all sentiment types**: The total number of reviews, including negative ones, has generally increased over time, particularly in early 2024 (March, April, May, July, August). This suggests increased user engagement, but also a proportional increase in negative feedback.
*   **Fluctuations in Negative Sentiment**: While the absolute number of negative reviews has grown, its proportion relative to positive reviews might fluctuate. Analyzing the ratios could provide deeper insights into whether the *rate* of negative feedback is changing.

### **3. Common Issues in Negative Reviews**

The "Common Issues in Negative Reviews" word cloud and the "Top Meaningful Issues (TF-IDF Phrases)" bar chart clearly point to specific problems:

*   **Technical Glitches**: Phrases like 'error code', 'connection failed', 'application slow', 'not working', 'unable login', 'crashes' are prominent, indicating frequent technical issues, bugs, and performance problems.
*   **User Experience (UX) Issues**: Terms like 'annoying issue', 'biggest problem', 'hard access', 'difficult use' suggest challenges with the interface, accessibility, or general usability.
*   **Functional Limitations**: Although less explicit in the current  output, if keywords like 'wrong answer', 'incorrect' were more prominent, they would point to issues with the AI's core functionality.

## **RECOMMENDATIONS FOR CHATGPT IMPROVEMENT**

Based on the identified issues, here are actionable recommendations for ChatGPT:

### **1. Enhance Stability and Performance**

*   **Prioritize Bug Fixes**: Address the 'error code', 'connection failed', 'application slow', and 'not working' issues. This will significantly improve user satisfaction and reliability.
*   **Optimize Performance**: Investigate and resolve causes of slowness and crashes to ensure a smooth user experience, especially during peak usage.
*   **Improve Login Experience**: The 'unable login' issue is critical as it prevents users from accessing the service. Streamline the login process and provide clearer error messages and recovery options.

### **2. Improve User Experience and Interface**

*   **Simplify Accessibility**: Tackle 'hard access' and 'difficult use' complaints by conducting thorough UX audits and user testing. Make the platform more intuitive and user-friendly.
*   **Clear Error Messaging**: Instead of generic 'error' messages, provide specific and actionable feedback to users about what went wrong and how they can resolve it.

### **3. Strengthen Customer Support & Communication**

*   **Proactive Communication**: For known widespread issues (e.g., service outages, performance degradation), communicate proactively with users through in-app notifications or social media to manage expectations.
*   **Feedback Loop**: Ensure there's an easy and efficient way for users to report bugs and provide detailed feedback, and that this feedback is actively monitored and acted upon.

### **4. Continuous Monitoring**

*   **Track Key Metrics**: Continuously monitor sentiment trends and issue frequencies. Look for spikes in negative sentiment and new recurring issues to address them promptly.
*   **A/B Testing**: Implement A/B testing for new features or UI changes to gauge their impact on user sentiment and usability before a full rollout.
"""